# Site settings
title: 
email: 
description: > # this means to ignore newlines until "baseurl:"
  Philly Python Workshop is part of the Philadelphia Python Users Group and runs introductory Python workshops.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: PhillyPythonWS
github_username:  PhillyPythonWorkshop
# Build settings
markdown: kramdown
