# Site settings
title: 
email: 
description: > # this means to ignore newlines until "baseurl:"
  PyStar Philly is part of the Philadelphia Python Users Group and leads Python workshops for women.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: pystarphilly
github_username:  PyStarPhilly

# Build settings
markdown: kramdown
